# Copyright (C) 2024 The apca Developers
# SPDX-License-Identifier: GPL-3.0-or-later

# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 25
    rebase-strategy: auto
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    versioning-strategy: auto
    directory: /
    schedule:
      interval: daily
